### ISSUE TITLE
Docs Issue: Recilieny

### ISSUE THREAD

**Issue by joebowbeer** [diagridio/conductor-feedback#2]
**Describe the issue**
s/Recilieny/Resiliency/

**URL of the docs**
https://docs.diagrid.io/conductor/insights/clusters#resiliency-policies

**Expected content**
Correct spelling

**Screenshots**

**Additional context**
Please make it easier to report issues by adding a GitHub link to the top of each page or a link to provide feedback at the bottom of each page.

**Comment by bibryam** [comment]
This is fixed, thanks for reporting!
